
from stix2 import TLP_AMBER, TLP_GREEN, TLP_RED, TLP_WHITE

X_OPENCTI_ALIASES = "x_opencti_aliases"
X_OPENCTI_ORGANIZATION_TYPE = "x_opencti_organization_type"
X_OPENCTI_RELIABILITY = "x_opencti_reliability"
X_OPENCTI_LOCATION_TYPE = "x_opencti_location_type"
X_MITRE_ID = "x_mitre_id"
X_OPENCTI_REPORT_STATUS = "x_opencti_report_status"
X_OPENCTI_SCORE = "x_opencti_score"
X_OPENCTI_LABELS = "x_opencti_labels"
X_OPENCTI_CREATED_BY_REF = "x_opencti_created_by_ref"
X_OPENCTI_MAIN_OBSERVABLE_TYPE = "x_opencti_main_observable_type"
X_OPENCTI_EXTERNAL_REFERENCES = "x_opencti_external_references"

DEFAULT_X_OPENCTI_SCORE = 50

INDICATOR_TYPE_MAPPING = {
    "domain": {
        "pattern": "[domain-name:value = '{value}']",
        "observable_type": "Domain-Name"
    },
    "ip": {
        "pattern": "[ipv4-addr:value = '{value}']",
        "observable_type": "IPv4-Addr",
    },
    "md5": {
        "pattern": "[file:hashes.'MD5' = '{value}']",
        "observable_type": "StixFile",
    },
    "sha1": {
        "pattern": "[file:hashes.'SHA-1' = '{value}']",
        "observable_type": "StixFile",
    },
    "sha256": {
        "pattern": "[file:hashes.'SHA-256' = '{value}']",
        "observable_type": "StixFile",
    },
        "url": {
        "pattern": "[url:value = '{value}']",
        "observable_type": "StixFile",
    },
}

STIX_TLP_MAP = {
    "white": TLP_WHITE,
    "green": TLP_GREEN,
    "amber": TLP_AMBER,
    "red": TLP_RED,
}

CONFIDENCE_MAP = {
    "low": 40,
    "moderate": 60,
    "high": 100,   
}

THREAT_LEVEL_MAP = {
    1: 90,
    2: 60,
    3: 30
}

GEOGRAPHIC_LOCATION_TYPE_MAP = {
    "Africa": "Region",
    "Northern Africa": "Region",
    "Algeria": "Country",
    "Egypt": "Country",
    "Libya": "Country",
    "Morocco": "Country",
    "Sudan": "Country",
    "Tunisia": "Country",
    "Western Sahara": "Country",
    "Sub-Saharan Africa": "Region",
    "British Indian Ocean Territory": "Country",
    "Burundi": "Country",
    "Comoros": "Country",
    "Djibouti": "Country",
    "Eritrea": "Country",
    "Ethiopia": "Country",
    "French Southern Territories": "Country",
    "Kenya": "Country",
    "Madagascar": "Country",
    "Malawi": "Country",
    "Mauritius": "Country",
    "Mayotte": "Country",
    "Mozambique": "Country",
    "R\u00e9union": "Country",
    "Rwanda": "Country",
    "Seychelles": "Country",
    "Somalia": "Country",
    "South Sudan": "Country",
    "Uganda": "Country",
    "United Republic of Tanzania": "Country",
    "Zambia": "Country",
    "Zimbabwe": "Country",
    "Angola": "Country",
    "Cameroon": "Country",
    "Central African Republic": "Country",
    "Chad": "Country",
    "Congo": "Country",
    "Democratic Republic of the Congo": "Country",
    "Equatorial Guinea": "Country",
    "Gabon": "Country",
    "Sao Tome and Principe": "Country",
    "Botswana": "Country",
    "Eswatini": "Country",
    "Lesotho": "Country",
    "Namibia": "Country",
    "South Africa": "Country",
    "Benin": "Country",
    "Burkina Faso": "Country",
    "Cabo Verde": "Country",
    "C\u00f4te d\u2019Ivoire": "Country",
    "Gambia": "Country",
    "Ghana": "Country",
    "Guinea": "Country",
    "Guinea-Bissau": "Country",
    "Liberia": "Country",
    "Mali": "Country",
    "Mauritania": "Country",
    "Niger": "Country",
    "Nigeria": "Country",
    "Saint Helena": "Country",
    "Senegal": "Country",
    "Sierra Leone": "Country",
    "Togo": "Country",
    "Americas": "Region",
    "Latin America and the Caribbean": "Region",
    "Anguilla": "Country",
    "Antigua and Barbuda": "Country",
    "Aruba": "Country",
    "Bahamas": "Country",
    "Barbados": "Country",
    "Bonaire": "Country",
    "British Virgin Islands": "Country",
    "Cayman Islands": "Country",
    "Cuba": "Country",
    "Cura\u00e7ao": "Country",
    "Dominica": "Country",
    "Dominican Republic": "Country",
    "Grenada": "Country",
    "Guadeloupe": "Country",
    "Haiti": "Country",
    "Jamaica": "Country",
    "Martinique": "Country",
    "Montserrat": "Country",
    "Puerto Rico": "Country",
    "Saint Barth\u00e9lemy": "Country",
    "Saint Kitts and Nevis": "Country",
    "Saint Lucia": "Country",
    "Saint Martin (French Part)": "Country",
    "Saint Vincent and the Grenadines": "Country",
    "Sint Maarten (Dutch part)": "Country",
    "Trinidad and Tobago": "Country",
    "Turks and Caicos Islands": "Country",
    "United States Virgin Islands": "Country",
    "Belize": "Country",
    "Costa Rica": "Country",
    "El Salvador": "Country",
    "Guatemala": "Country",
    "Honduras": "Country",
    "Mexico": "Country",
    "Nicaragua": "Country",
    "Panama": "Country",
    "Argentina": "Country",
    "Bolivia (Plurinational State of)": "Country",
    "Bouvet Island": "Country",
    "Brazil": "Country",
    "Chile": "Country",
    "Colombia": "Country",
    "Ecuador": "Country",
    "Falkland Islands (Malvinas)": "Country",
    "French Guiana": "Country",
    "Guyana": "Country",
    "Paraguay": "Country",
    "Peru": "Country",
    "South Georgia and the South Sandwich Islands": "Country",
    "Suriname": "Country",
    "Uruguay": "Country",
    "Venezuela (Bolivarian Republic of)": "Country",
    "Northern America": "Region",
    "Bermuda": "Country",
    "Canada": "Country",
    "Greenland": "Country",
    "Saint Pierre and Miquelon": "Country",
    "United States of America": "Country",
    "Asia": "Region",
    "Central Asia": "Region",
    "Kazakhstan": "Country",
    "Kyrgyzstan": "Country",
    "Tajikistan": "Country",
    "Turkmenistan": "Country",
    "Uzbekistan": "Country",
    "Eastern Asia": "Region",
    "China": "Country",
    "Hong Kong Special Administrative Region": "Country",
    "Macao Special Administrative Region": "Country",
    "Democratic People's Republic of Korea": "Country",
    "Japan": "Country",
    "Mongolia": "Country",
    "Republic of Korea": "Country",
    "Taiwan": "Country",
    "South-eastern Asia": "Region",
    "Brunei Darussalam": "Country",
    "Cambodia": "Country",
    "Indonesia": "Country",
    "Lao People's Democratic Republic": "Country",
    "Malaysia": "Country",
    "Myanmar": "Country",
    "Philippines": "Country",
    "Singapore": "Country",
    "Thailand": "Country",
    "Timor-Leste": "Country",
    "Viet Nam": "Country",
    "Southern Asia": "Region",
    "Afghanistan": "Country",
    "Bangladesh": "Country",
    "Bhutan": "Country",
    "India": "Country",
    "Iran (Islamic Republic of)": "Country",
    "Maldives": "Country",
    "Nepal": "Country",
    "Pakistan": "Country",
    "Sri Lanka": "Country",
    "Middle East": "Region",
    "Armenia": "Country",
    "Azerbaijan": "Country",
    "Bahrain": "Country",
    "Georgia": "Country",
    "Iraq": "Country",
    "Israel": "Country",
    "Jordan": "Country",
    "Kuwait": "Country",
    "Lebanon": "Country",
    "Oman": "Country",
    "Qatar": "Country",
    "Saudi Arabia": "Country",
    "State of Palestine": "Country",
    "Syrian Arab Republic": "Country",
    "Turkey": "Country",
    "United Arab Emirates": "Country",
    "Yemen": "Country",
    "Cyprus": "Country",
    "Europe": "Region",
    "Eastern Europe": "Region",
    "Belarus": "Country",
    "Bulgaria": "Country",
    "Czechia": "Country",
    "Hungary": "Country",
    "Poland": "Country",
    "Republic of Moldova": "Country",
    "Romania": "Country",
    "Russian Federation": "Country",
    "Slovakia": "Country",
    "Ukraine": "Country",
    "Northern Europe": "Region",
    "\u00c5land Islands": "Country",
    "Guernsey": "Country",
    "Jersey": "Country",
    "Sark": "Country",
    "Denmark": "Country",
    "Estonia": "Country",
    "Faroe Islands": "Country",
    "Finland": "Country",
    "Iceland": "Country",
    "Ireland": "Country",
    "Isle of Man": "Country",
    "Latvia": "Country",
    "Lithuania": "Country",
    "Norway": "Country",
    "Svalbard and Jan Mayen Islands": "Country",
    "Sweden": "Country",
    "United Kingdom of Great Britain and Northern Ireland": "Country",
    "Southern Europe": "Region",
    "Albania": "Country",
    "Andorra": "Country",
    "Bosnia and Herzegovina": "Country",
    "Croatia": "Country",
    "Gibraltar": "Country",
    "Greece": "Country",
    "Holy See": "Country",
    "Italy": "Country",
    "Malta": "Country",
    "Montenegro": "Country",
    "North Macedonia": "Country",
    "Portugal": "Country",
    "San Marino": "Country",
    "Serbia": "Country",
    "Slovenia": "Country",
    "Spain": "Country",
    "Western Europe": "Region",
    "Austria": "Country",
    "Belgium": "Country",
    "France": "Country",
    "Germany": "Country",
    "Liechtenstein": "Country",
    "Luxembourg": "Country",
    "Monaco": "Country",
    "Netherlands": "Country",
    "Switzerland": "Country",
    "Oceania": "Region",
    "Australia and New Zealand": "Region",
    "Australia": "Country",
    "Christmas Island": "Country",
    "Cocos (Keeling) Islands": "Country",
    "Heard Island and McDonald Islands": "Country",
    "New Zealand": "Country",
    "Norfolk Island": "Country",
    "Melanesia": "Region",
    "Fiji": "Country",
    "New Caledonia": "Country",
    "Papua New Guinea": "Country",
    "Solomon Islands": "Country",
    "Vanuatu": "Country",
    "Micronesia": "Region",
    "Guam": "Country",
    "Kiribati": "Country",
    "Marshall Islands": "Country",
    "Micronesia (Federated States of)": "Country",
    "Nauru": "Country",
    "Northern Mariana Islands": "Country",
    "Palau": "Country",
    "United States Minor Outlying Islands": "Country",
    "Polynesia": "Region",
    "American Samoa": "Country",
    "Cook Islands": "Country",
    "French Polynesia": "Country",
    "Niue": "Country",
    "Pitcairn": "Country",
    "Samoa": "Country",
    "Tokelau": "Country",
    "Tonga": "Country",
    "Tuvalu": "Country",
    "Wallis and Futuna Islands": "Country",
    "Antarctica": "Country"
}