version: '3'
services:
  connector-arctichub:
    image: opencti/connector-arctichub:6.2.4
    environment:
      # Connector's generic execution parameters
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=CHANGEME
      # Connector's definition parameters REQUIRED
      - CONNECTOR_ID=CHANGEME
      - CONNECTOR_NAME=Arctichub
      - CONNECTOR_SCOPE=arctichub
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_DURATION_PERIOD=PT24H # ISO8601 format in String, start with 'P...' for Period
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      # Connector's definition parameters OPTIONAL
      # - CONNECTOR_QUEUE_THRESHOLD=500 # Default 500Mo, Float accepted
      # - CONNECTOR_RUN_AND_TERMINATE=False # Default False, True run connector once
      # - CONNECTOR_SEND_TO_QUEUE=True # Default True
      # - CONNECTOR_SEND_TO_DIRECTORY=False # Default False 
      # - CONNECTOR_SEND_TO_DIRECTORY_PATH=CHANGEME # if CONNECTOR_SEND_TO_DIRECTORY is True, you must specify a path
      # - CONNECTOR_SEND_TO_DIRECTORY_RETENTION=7 # Default 7, in days

      # Connector's custom execution parameters
      - CONNECTOR_ARCTICHUB_API_BASE_URL='https://cert-be.arcticsecurity.com:9443/api'
      - CONNECTOR_ARCTICHUB_API_EVENTS_PATH='storage/v1/events'
      - CONNECTOR_ARCTICHUB_API_CUSTOMERS_PATH='config/v1/export/customers'
      - CONNECTOR_ARCTICHUB_API_EVENTS_KEY=CHANGEME
      - CONNECTOR_ARCTICHUB_API_CUSTOMERS_KEY=CHANGEME
      - CONNECTOR_IP_CIDR_EXPANSION=false
      - CONNECTOR_IP_CIDR_EXPANSION_MAX_HOST_SIZE=8192
      - CONNECTOR_IP_CIDR_EXPANSION_PRIVATE_NETWORKS=false
      - CUSTOMERS_IGNORED_NAMES="Siebe test sync template"

      # Add proxy parameters below if needed
      # - HTTP_PROXY=CHANGEME
      # - HTTPS_PROXY=CHANGEME
      # - NO_PROXY=CHANGEME
    restart: always
    # networks:
    #   - docker_default

# networks:
#   default:
#     external: true
#     name: docker_default
