services:
  connector-dragos:
    image: opencti/connector-dragos:6.2.18
    environment:
      # OpenCTI platform
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=CHANGEME
      # Connector identification
      - CONNECTOR_ID=CHANGEME
      - CONNECTOR_NAME=Dragos
      - CONNECTOR_SCOPE=dragos
      # Connector execution
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_DURATION_PERIOD=PT6H # Interval given for scheduler process in ISO-8601 format
      # Dragos Portal API
      - CONNECTOR_DRAGOS_API_BASE_URL=https://portal.dragos.com/api/v1/
      - CONNECTOR_DRAGOS_API_ACCESS_TOKEN=CHANGEME
      - CONNECTOR_DRAGOS_API_ACCESS_KEY=CHANGEME
      - CONNECTOR_DRAGOS_START_DATE=2024-01-01
      - CONNECTOR_DRAGOS_REQUESTS_PER_MINUTE_LIMIT=30
      - CONNECTOR_DRAGOS_REQUESTS_PER_MINUTE_LIMIT=250
    restart: always
    # networks:
    #   - docker_default

# networks:
#   default:
#     external: true
#     name: docker_default